const express = require('express')

const router = express.Router()

const auth = require('./auth')
const category = require('./category')
const customer = require('./customer')
const employee = require('./employee')
const order = require('./order')
const orderLine = require('./order-line')
const orderStatus = require('./order-status')
const productImage = require('./product-image')
const product = require('./product')
const role = require('./role')
const cart = require('./cart')
const cartLine = require('./cart-line')
const movie = require('./movie')
const ticket = require('./ticket')
const seat = require('./seat')
const threater = require('./threater')
const showTime = require('./show-time')

router.use('/auth', auth)
router.use('/categories', category)
router.use('/customers', customer)
router.use('/employees', employee)
router.use('/orders', order)
router.use('/order-lines', orderLine)
router.use('/order-statuses', orderStatus)
router.use('/product-images', productImage)
router.use('/products', product)
router.use('/roles', role)
router.use('/carts', cart)
router.use('/cart-lines', cartLine)
router.use('/movies', movie)
router.use('/tickets', ticket)
router.use('/seats', seat)
router.use('/show-times', showTime)
router.use('/threaters', threater)

module.exports = router
